services:
  omeka-s:
    build: ./
    networks:
      - my-network
    ports:
      - "9018:80"
    volumes:
      - ./modules/:/var/www/html/materialendatabank/modules/
      - ./themes/:/var/www/html/materialendatabank/themes/
      - /files/:/var/www/html/materialendatabank/files/
      - ./config/:/var/www/html/materialendatabank/config/
      - ./.htaccess:/var/www/html/materialendatabank/.htaccess
    restart: "no"

networks:
  my-network:
    external:
      name: dev-network