<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var \Guest\Form\EmailForm $form
 */

$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'guest account');
$form->prepare();
$siteSlug = $this->params()->fromRoute('site-slug');
?>
<div class="container">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/materialendatabank">Home</a></li>
      
      <li class="breadcrumb-item"><a href="/materialendatabank/s/<?php echo $siteSlug;?>/guest/">Account</a></li>
                 
      <li class="breadcrumb-item active" aria-current="page">E-mail</li>
      
    </ol>

    <?= $this->messages() ?>

    <?= $this->pageTitle($translate('Mijn e-mail')) ?>

    <?= $this->form()->openTag($form) ?>
    <?= $this->formCollection($form, false) ?>
    <?php $this->trigger('view.add.form.after'); ?>
    <div id="page-actions">
        <button class="btn" type="submit"><?= $translate('Update') ?></button>
    </div>
    <?= $this->form()->closeTag() ?>

    <?php $this->trigger('view.add.after'); ?>
</div>