<?php if($block->dataValue('text')):?>
<section class="section">
<?php else:?>
<section class="section">
<?php endif?>
    <div class="container">
      <?php if($block->dataValue('title')):?>
        <h3 class="title is-5"><?php echo $block->dataValue('title');?></h3>
      <?php endif;?>
      <div class="row">
        <?php if($block->dataValue('text') && !$block->dataValue('text2')):?>
          <div class="col-md-12">
              <div class="card card-gray">
                <div class="card-body">         
                <?php echo $block->dataValue('text');?>
                </div>
              </div>  
          </div>
        <?php endif;?>
        <?php if($block->dataValue('text') && $block->dataValue('text2')):?>
          <div class="col-md-6">
            <div class="card card-gray">
              <div class="card-body">
                <?php echo $block->dataValue('text');?>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card card-gray">
              <div class="card-body">
              <?php echo $block->dataValue('text2');?>
              </div>
            </div>
          </div>
        <?php endif;?>
      </div>    
    </div>
</section>
