<?php
$translate = $this->plugin('translate');
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
?>
  <form class="has-icons-right" action="http://localhost:9018/tdc/s/tdc/item" id="search-form">
    <div class="field has-addons">
      <div class="control">
        <input style="color: initial" class="input is-medium is-rounded" type="text" name="fulltext_search" value="<?php echo $searchValue; ?>"
            placeholder="<?php echo $translate('Search'); ?>"
            aria-label="<?php echo $translate('Search'); ?>">
      </div>
      <div class="control">
        <button class="button is-info is-medium">
          <span class="icon is-large">
            <i class="fas fa-search"></i>
          </span>
        </button>
      </div>
    </div>
  </form>
